codecheck:
  image: ubuntu
  tags:
    - empaia-parallel
  before_script:
    - apt-get update -q && apt-get install -y -qq clang-format-10 git
  script:
    - ./clang-format.sh

build-wsi-anon:
  image: emscripten/emsdk
  tags:
    - empaia-parallel
  script:
    - make
    - make wasm
  artifacts:
    paths:
      - bin

test-wsi-anon:
  image: emscripten/emsdk
  tags:
    - empaia-parallel
  script:
    - apt-get update -q && apt-get install -yq libcunit1-dev
    - make tests
    - bin/utests
  artifacts:
    paths:
      - Test-Wsi-Anon-Results.xml

publish-wsi-anon-package:
  only:
    - master
  image: node:16-slim
  tags:
    - empaia-parallel
  needs:
    - job: codecheck
    - job: test-wsi-anon
    - job: build-wsi-anon
      artifacts: true
  script:
    - echo '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}' > .npmrc
    - npm publish --registry https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/
