stages:
  - build
  - publish

build-wsi-anon-wasm:
  stage: build
  image: emscripten/emsdk
  tags:
    - empaia-charite
  variables:
    HTTP_PROXY: "http://proxy.charite.de:8080"
    HTTPS_PROXY: "http://proxy.charite.de:8080"
    NO_PROXY: "localhost,127.0.0.1"
    http_proxy: "http://proxy.charite.de:8080"
    https_proxy: "http://proxy.charite.de:8080"
    no_proxy: "localhost,127.0.0.1"
  script:
    - make wasm
    - ls -lha ./bin

publish-wsi-anon-package:
  stage: publish
  rules:
    - if: '$CI_COMMIT_TAG =~ /^wsi\-anon\-\d+.\d+.\d+/'
  image: node:16-slim
  tags:
    - empaia-charite
  variables:
    HTTP_PROXY: "http://proxy.charite.de:8080"
    HTTPS_PROXY: "http://proxy.charite.de:8080"
    NO_PROXY: "localhost,127.0.0.1"
    http_proxy: "http://proxy.charite.de:8080"
    https_proxy: "http://proxy.charite.de:8080"
    no_proxy: "localhost,127.0.0.1"
  script:
    - echo '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}' > .npmrc
    - npm publish $CI_PROJECT_DIR/dist/libs/slide-viewer --registry https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/
