stages:
  - codecheck
  - build
  - test
  - publish

variables: &proxy_settings
  HTTP_PROXY: 'http://proxy.charite.de:8080'
  HTTPS_PROXY: 'http://proxy.charite.de:8080'
  NO_PROXY: 'localhost,127.0.0.1'
  http_proxy: 'http://proxy.charite.de:8080'
  https_proxy: 'http://proxy.charite.de:8080'
  no_proxy: 'localhost,127.0.0.1'

codecheck:
  stage: codecheck
  tags:
    - empaia-charite
  before_script:
    - apt-get update -q && apt-get install -yq clang-format-10
  script:
    - ./clang-format.sh

build-wsi-anon:
  stage: build
  image: emscripten/emsdk
  tags:
    - empaia-charite
  script:
    - make
    - make wasm
  artifacts:
    paths:
      - bin

test-wsi-anon:
  stage: test
  image: emscripten/emsdk
  tags:
    - empaia-charite
  script:
    - apt-get update -q && apt-get install -yq libcunit1-dev
    - make tests
    - bin/utests
  artifacts:
    paths:
      - Test-Wsi-Anon-Results.xml

publish-wsi-anon-package:
  stage: publish
  only:
    - master
  dependencies:
    - build-wsi-anon
  image: node:16-slim
  tags:
    - empaia-charite
  script:
    - echo '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}' > .npmrc
    - npm publish --registry https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/
