stages:
  - codecheck
  - build
  - test
  - publish

variables: &proxy_settings
  HTTP_PROXY: 'http://proxy.charite.de:8080'
  HTTPS_PROXY: 'http://proxy.charite.de:8080'
  NO_PROXY: 'localhost,127.0.0.1'
  http_proxy: 'http://proxy.charite.de:8080'
  https_proxy: 'http://proxy.charite.de:8080'
  no_proxy: 'localhost,127.0.0.1'

codecheck:
  stage: codecheck
  tags:
    - empaia-charite
  before_script:
    - apt-get update -q && apt-get install -y -qq clang-format-10 git
  script:
    - ./clang-format.sh

build-wsi-anon:
  stage: build
  image: emscripten/emsdk
  tags:
    - empaia-charite
  script:
    - make
    - make wasm
  artifacts:
    paths:
      - bin

test-unit:
  stage: test
  image: emscripten/emsdk
  tags:
    - empaia-charite
  script:
    - apt-get update -q && apt-get install -yq libcunit1-dev
    - make tests
    - bin/utests
  artifacts:
    paths:
      - Test-Wsi-Anon-Results.xml

test-integration:
  stage: test
  image: registry.gitlab.com/empaia/integration/test-runner
  variables:
    <<: *proxy_settings
    HTTP_PROXY: ''
    HTTPS_PROXY: ''
    NO_PROXY: ''
    http_proxy: ''
    https_proxy: ''
    no_proxy: ''
  tags:
    - empaia-docker
    - testdata
  before_script:
    - cp sample.env .env
    - docker-compose -f docker-compose.test.yml up -d --build
  script:
    - docker exec wsi-anon_wsi-anon_1 pytest wrapper/python/test
  after_script:
    - docker-compose -f docker-compose.test.yml down

publish-wsi-anon-package:
  stage: publish
  only:
    - master
  dependencies:
    - build-wsi-anon
  image: node:16-slim
  tags:
    - empaia-charite
  script:
    - echo '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}' > .npmrc
    - npm publish --registry https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/
